  web:
    build: .
    ports:
    - "9013:9013"
    links:
    - redis:redis
    - nginx:nginx
    env_file: .env
    volumes:
    - .:/code
  #  command: /code/manage.py runserver 0.0.0.0:8000


  redis:
    image: daocloud.io/redis:3.0
#    image: redis:latest
    ports:
    - "6379:6379"
  nginx:
    image: daocloud.io/nginx
    ports:
    - "80:80"
